#!/bin/sh

# make sure error return codes are as expected useful cases
# (e.g. commands to check ruleset state)

global_rc=0

cmd() { # (rc, cmd, [args ...])
	rc_exp=$1; shift

	$XT_MULTI "$@"
	rc=$?

	[ $rc -eq $rc_exp ] || {
		echo "---> expected $rc_exp, got $rc for command '$@'"
		global_rc=1
	}
}

# test chain creation
cmd 0 iptables -N foo
cmd 1 iptables -N foo
# iptables-nft allows this - bug or feature?
#cmd 2 iptables -N "invalid name"

# test chain rename
cmd 0 iptables -E foo bar
cmd 1 iptables -E foo bar

# test rule adding
cmd 0 iptables -A INPUT -j ACCEPT
cmd 1 iptables -A noexist -j ACCEPT

# test rule checking
cmd 0 iptables -C INPUT -j ACCEPT
cmd 1 iptables -C FORWARD -j ACCEPT
cmd 1 iptables -C nonexist -j ACCEPT
cmd 2 iptables -C INPUT -j foobar
cmd 2 iptables -C INPUT -m foobar -j ACCEPT
cmd 3 iptables -t foobar -C INPUT -j ACCEPT

exit $global_rc
