#!/bin/bash

[[ $XT_MULTI == *xtables-nft-multi ]] || { echo "skip $XT_MULTI"; exit 0; }
nft -v >/dev/null || exit 0

set -e

nft -f - <<EOF
table ip filter {
	chain FORWARD {
		type filter hook forward priority filter;
		limit rate 10/day counter
		udp dport 42 counter
	}
}
EOF

EXPECT="*filter
:INPUT ACCEPT [0:0]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
-A FORWARD -m limit --limit 10/day
-A FORWARD -p udp -m udp --dport 42
COMMIT"

diff -u -Z <(echo -e "$EXPECT") <($XT_MULTI iptables-save | grep -v '^#')
