#!/bin/sh

set -x
case "$XT_MULTI" in
*/xtables-nft-multi)
	for t in filter nat;do
		$XT_MULTI ebtables -t $t -L || exit 1
		$XT_MULTI ebtables -t $t -X || exit 1
		$XT_MULTI ebtables -t $t -F || exit 1
	done

	for t in broute foobar ;do
		$XT_MULTI ebtables -t $t -L &&
		$XT_MULTI ebtables -t $t -X &&
		$XT_MULTI ebtables -t $t -F
		if [ $? -eq 0 ]; then
			echo "Expect nonzero return for unsupported table"
			exit 1
		fi
	done


	$XT_MULTI ebtables -t filter -N FOO || exit 1
	$XT_MULTI ebtables -t filter -N FOO
	if [ $? -eq 0 ]; then
		echo "Duplicate chain FOO"
		$XT_MULTI ebtables -t filter -L
		exit 1
	fi

	$XT_MULTI ebtables -L FOO | grep -q 'entries: 0'
	if [ $? -ne 0 ]; then
		echo "Unexpected entries count in empty unreferenced chain"
		$XT_MULTI ebtables -L
		exit 1
	fi

	$XT_MULTI ebtables -A FORWARD -j FOO
	$XT_MULTI ebtables -L FORWARD | grep -q 'entries: 1'
	if [ $? -ne 0 ]; then
		echo "Unexpected entries count in FORWARD chain"
		$XT_MULTI ebtables -L
		exit 1
	fi

	$XT_MULTI ebtables -L FOO | grep -q 'entries: 0'
	if [ $? -ne 0 ]; then
		echo "Unexpected entries count in empty referenced chain"
		$XT_MULTI ebtables -L
		exit 1
	fi

	$XT_MULTI ebtables -A FOO -j ACCEPT
	$XT_MULTI ebtables -L FOO | grep -q 'entries: 1'
	if [ $? -ne 0 ]; then
		echo "Unexpected entries count in non-empty referenced chain"
		$XT_MULTI ebtables -L
		exit 1
	fi

	$XT_MULTI ebtables -t filter -N BAR || exit 1
	$XT_MULTI ebtables -t filter -N BAZ || exit 1

	$XT_MULTI ebtables -t filter -L | grep -q FOO || exit 1
	$XT_MULTI ebtables -t filter -L | grep -q BAR || exit 1
	$XT_MULTI ebtables -t filter -L | grep -q BAZ || exit 1

	$XT_MULTI ebtables -t filter -L BAZ || exit 1
	$XT_MULTI ebtables -t filter -X BAZ || exit 1
	$XT_MULTI ebtables -t filter -L BAZ | grep -q BAZ
	if [ $? -eq 0 ]; then
		echo "Deleted chain -L BAZ ok, expected failure"
		$XT_MULTI ebtables -t filter -L
		exit 1
	fi

	$XT_MULTI ebtables -t $t -F || exit 0
	;;
*)
	echo "skip $XT_MULTI"
	;;
esac
