#!/bin/bash

case $XT_MULTI in
*xtables-nft-multi)
	;;
*)
	echo skip $XT_MULTI
	exit 0
	;;
esac

set -e

nft -f - <<EOF
table ip filter {
        chain INPUT {
                type filter hook input priority filter
                counter packets 218 bytes 91375 accept
        }

        chain x {
                type filter hook input priority filter
        }
}
EOF

$XT_MULTI iptables -L
